### ISSUE TITLE
parataxis:obj vs comp:obj

### ISSUE THREAD

**Issue by sylvainkahane** [surfacesyntacticud/guidelines#23]
We are finishing a paper for the syntaxfest about the annotation of spoken treebanks and we discuss the `parataxis` relation. We noted some inconsistencies between our two treebanks of spoken languages, French and Naija.
In Naija, according to UD, `parataxis` is favored and we have `parataxis:obj` for reported speech (_I said don't do that_), `parataxis:discourse` for clausal discourse marker (_it is ok you know_), `parataxis:dislocated` for clausal prenucleus (_j'ai ma voiture elle est en panne_), `parataxis:mod` for clausal modifiers without markers (_on n'a beau essayé on y arrive pas; tu me l'aurais dit j'y serai allé; tu y vas tu y vas pas c'est pareil_).
In French, we hesitated and also use `comp:obj`, `discourse`, `dislocated` or `mod` for these constructions. The reason is the following principle of SUD: if two units are in the same paradigm of commutation, they have the same syntactic function. For instance a reported speech can commute with a governed object (_I said not to do that, I said that I disagreed_), which justify to use the same relation in both case (a feature `Reported=Yes` can be added). In the other cases, the commutation is less evident, even though it can be defended (_j'ai ma voiture_ can commute with _ma voiture_ in _j'ai ma voiture elle est en panne_).
What do you think we should do in SUD? In any case, in UD, `parataxis` will be introduced during the conversion and `parataxis:subrel` will be used.

**Comment by perrier54** [comment]
In [SUD_French-GSD](https://github.com/surfacesyntacticud/SUD_French-GSD), there is no ambiguity between `parataxis`, `comp:obj` and `dislocated` relations.

For reported speech,  we use `parataxis` if the reported speech appears first.

_"I am coming", he said_  
am -[parataxis]-> said

If the reported speech appears afterwards, we use `comp:obj`.
_he said, "I am coming"_
said -[comp:obj]-> am
This is why I don't agree to use `parataxis`in this case. _"I am coming"_ commutes with _that I am coming_.

The relation `dislocated` is used when a nominal at the beginning or end of a clause is repeated by a pronoun in the clause.
_John, I know him_
know -[dislocated]- > John

For the example _"j'ai ma voiture, elle est en panne"_, I think it's best to use _ai -[parataxis]-> est._ The `dislocated` relation  should be discarded because _"j'ai ma voiture"_ is not a nominal and we can rather commute _"elle est en panne"_ with _"qui est en panne"_ in the sentence _"j'ai ma voiture elle est en panne"_.

**Comment by Julie921** [comment]
For direct speech, we chose this annotation :
"Direct discourse is attached its governor by the relation comp:obj with the features Reported = “Yes”."
It is already in the guidelines. I close the issue.

**Comment by perrier54** [comment]
Do we agree that for incisive proposal indicating who reports, the relation is `parataxis`.

Examples : _" il arrive, dit-il, demain soir"_ ("he arrives, he says, tomorrow night")
_"il arrive demain soir", dit-il_  ("he arrives tomorrow night", he says)

**Comment by sylvainkahane** [comment]
Yes. In our spoken corpora, we distinguish parentheses and inserts (Fr. _incise_) and use `parataxis:parenth` vs `parataxis:insert`.
http://universal.grew.fr/?custom=63fa5a201b667
