### ISSUE TITLE
Pronominal verbs

### ISSUE THREAD

**Issue by perrier54** [surfacesyntacticud/guidelines#26]
The [UD guidelines](https://universaldependencies.org/u/dep/expl.html) propose to use  `expl:pv` relations between pronominal verbs and their reflexive clitic. In SUD, I propose to use `comp@expl`.
Since they are not grammatical locutions, I propose not to label them with ` Idiom = Yes`.

Example: "_ils s'enfuient_ (they run away)" 
"enfuient" -[comp@expl]-> s'

**Comment by kimgerdes** [comment]
that looks reasoable for the reflexive clitics.
yet, it'll be a hard task to actually delimit the @expl extension, see https://github.com/UniversalDependencies/docs/issues/461

**Comment by AurelienSH** [comment]
Just to make sure, what I understood is that the feature `Reflex=True` should only be used for fixed expressions, but as you can see with this request : http://universal.grew.fr/?custom=629f169c7421b the feature has been added for every reflexive pronoun, does it need fixing or has the feature changed purpose ?

**Comment by AurelienSH** [comment]
Ok, here's what we have in mind regarding relations regarding reflexive pronouns :

First we gathered that the feature Reflex=Yes needs to be applied to pronouns having the same reference as the subject 
and that are placed between the tensed verb and the subject itself.

Here's a recap of every relation we found :

comp@expl :

For pronominal verbs i.e. verbs that can only be used with a relexive pronoun :
s'évaporer

This also applies to verbs that change meaning if used with a reflexive pronoun :
s'entendre

comp@pass :

For passive reflexive constructions :
Les livres se vendent bien

For these two we chose to give the lemma "se" to the pronoun since it doesn't relfect any grammatical or semantic meaning

__________

comp:obj :

For reflexive pronouns replacing direct object :
On s'est regardées


Here we chose to give the lemma "le" to the pronoun

__________


comp:obl :

For reflexive pronouns replacing oblique arguments :
Il m'a dit

Here we chose to give the lemma "lui" to the pronoun

__________

We haven't applied our rule regarding the Reflex feature yet but everything else should be ok 
Here's a request showing the changes (the corpus is updating as of now but it should be up to date soon enough) :
http://universal.grew.fr/?custom=62a336b84f480

**Comment by perrier54** [comment]
I am not convinced that differences in syntactic function should justify differences in lemma. In [SUD_French-GSD](https://github.com/surfacesyntacticud/SUD_French-GSD), we have the lemma _se_ in all cases.
