### ISSUE TITLE
Analysis of French verbs which require a reflexive pronoun but which are semantically not reflexive in nature.

### ISSUE THREAD

**Issue by MariamNakhle** [surfacesyntacticud/guidelines#3]
We are of the opinion that the actual analysis of the pronoun within the French so-called essentially pronominal verbs needs a further discussion.

In the example "Je me souviens" the pronoun "me" has no obvious relation to the verb.

Multiple solutions are possible:
- not precising the sub-relation: `comp`
- tagging it as something fixed: `comp@fixed`
- assigning a default sub-relation: `comp:obj` or `comp:obl`

**Comment by perrier54** [comment]
The problem is more general: it concerns all verbs that form a fixed expression with a pronoun that no longer plays the role of an argument of the verb.

> Examples in French:  
_Il en veut à son père (He's angry at his father)
Il s'en sort bien (He's doing well)
Il y a un problème (There is a problem)
Où en est-il ? (How's he doing?)_

To be consistent with my proposal regarding multi-word expressions (MWEs)#4, I consider these verbs with their pronouns as any MWEs.
The verb has the features _ExtPos=VERB_ and _Type=MWE,_ and the attached pronoun(s) has the feature _InMWE=Yes_. I propose to label the relation between the verb and the pronoun with _unk_ as for MWE without any known internal structure.
I think that _comp_ is not appropriate because the pronoun is not an argument of the verb.

> Example: _Il s'en sort bien_
sort [upos=VERB,ExtPos=VERB, Type=MWE]  --[unk]-> s'[upos=PRON, InMWE=Yes]
sort [upos=VERB,ExtPos=VERB, Type=MWE]  --[unk]-> en[upos=PRON, InMWE=Yes]

One problem remains: when the pronoun is separated from the verb by an auxiliary and possibly an adverb like in the sentence _"il s'en est bien sorti"_ .
When the pronoun is an argument of the verb, the relation remains between the verb and the pronoun. I propose to do the same when the pronoun forms a fixed expression with the verb.

> Example: _Il s'en est bien sorti_
sorti [upos=VERB,ExtPos=VERB, Type=MWE]  --[unk]-> s'[upos=PRON, InMWE=Yes]
sorti [upos=VERB,ExtPos=VERB, Type=MWE]  --[unk]-> en[upos=PRON, InMWE=Yes]

**Comment by kimgerdes** [comment]
i'm not convinced that the case of pronominal verbs fit well into @perrier54 's definition:
> Multi-word expressions (MWEs) and titles have the following property in common: their internal structure is not naturally integrated into the syntactic structure of the sentence; they are double-sided objects: on the one hand, they behave as atomic objects with the rest of the sentence, and on the other hand, they behave as a structure with its elements, and there is a break between the atomic object and the structure.

it's rather the contrary: they integrate so well into the normal argument structure that it is hard to recognize that they cannot be de-pronominalized. What is actually the criteria for receiving this special treatment? One criteria for MWE could be that upos != extpos. but that is probably too restrictive.

>  Il s'en sort bien (He's doing well)
is this really a different meaning from
> Il se sort bien de la misère
> Il s'est facilement sorti du trou. 
?

idem:
> Il y a un problème (There is a problem)
> Dans ce texte, il y a un problème quelquepart, mais je ne vois pas vraiment où.

Then there is the question of the relation to expletives. On which ground shall we distinguish these cases from
> Il pleut
?

I have the feeling that `unk` is somehow wrong. It's not an unknown relation, and it's certainly much more on the argument side of verbal dependents. What's more so is that we have the same problem with UD: the mwe rule is: annotate the POS but leave the dependency flat. that's a bit contradictory. If you determine the POS, you know the distributive class of the word, and quite a lot about the syntactic structure.

So I'd rather vote for `comp` 
And can't we shorten the feature structure to
`sort [upos=VERB,ExtPos=VERB, InMWE=MWE] --[comp]-> s'[upos=PRON, InMWE=MWE]`
?

Last but not least I'm a bit unhappy about the "type" MWE. that sound like we haven't found a better name. Title is a good name. Named Entity is clear. so what do we have here? how to name it?

**Comment by perrier54** [comment]
By analogy with clitic pronouns which are verbal arguments, I finally agree with `comp` for the relation between reflexive pronouns and the pronominal verbs, on which they depend.

**Comment by Julie921** [comment]
Obsolete annotation. See #26
